### ISSUE TITLE
Ivy Bridge-E

### ISSUE THREAD

**Issue by WajdiMuh** [Cclown98/X99-OPENCORE-EFI-CATALINA-BIGSUR#6]
can you please tell me what to do to get it working on ivy bridge-e

**Comment by andrescera** [comment]
CPUID1DATA  for IVY BRIDGE-E/EN/EP:
 E4060300 00000000 00000000 00000000
also was added to project README

**Comment by WajdiMuh** [comment]
Which acpi should i use for x79

**Comment by andrescera** [comment]
you can generate SSDT by using SSDTTIME on windows or linux https://github.com/corpnewt/SSDTTime

**Comment by WajdiMuh** [comment]
thx i got it working now a couple of probllems with usb 3.0 any ideas

**Comment by andrescera** [comment]
this tutorial made by @maLd0n can help you https://www.olarila.com/topic/9390-video-guide-usb-port-mapping-with-hackintool/

**Comment by WajdiMuh** [comment]
no they arent working at all i renamed using acpi patches but still usb 2.0 works

**Comment by andrescera** [comment]
> no they arent working at all i renamed using acpi patches but still usb 2.0 works

X79 Motherboards don't have USB 3.0 chipset, probably your are using an External  PCIe USB 3.0 Card or a build-in PCIe USB 3.0 Card  so you'll have to find a kext for it try looking for information on windows/linux them search for a compatible kext
